---
- name: Converge
  hosts: webservers
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
  remote_user: root
  vars:
    bbb_nodejs_version: 8.x
    bbb_hostname: bigbluebutton.kyt.academy
    bbb_coturn_secret: eE2xT6Byu7KjqQaOy2B3
    bbb_greenlight_enable: true
    bbb_greenlight_secret: 10iDiW43BcWjaBq73LdYvff4a5f
    bbb_greenlight_db_password: 0Le4Eq3G71VmQaRzktv39X1z
    bbb_letsencrypt_enable: true
    bbb_letsencrypt_email: sreeraj@kyt.academy
    bbb_nginx_dh: true
  tasks:
    - name: "Include n0emis.bigbluebutton"
      include_role:
        name: "n0emis.bigbluebutton"
